# Generated by Django 2.0.6 on 2018-06-09 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name': 'Статус тикета', 'verbose_name_plural': 'Статусы тикетов'},
        ),
    ]
