# Generated by Django 2.0.6 on 2018-06-09 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20180609_1738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketcategory',
            name='name',
        ),
        migrations.AddField(
            model_name='ticketcategory',
            name='status',
            field=models.ForeignKey(blank=True, default=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.status'),
        ),
    ]
