# Generated by Django 2.0.6 on 2018-06-09 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_ticket_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=models.ForeignKey(blank=True, default=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.status'),
        ),
    ]
