# Generated by Django 2.0.6 on 2018-06-21 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_ticket_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticketcategory',
            options={'verbose_name': 'Информация о тикете', 'verbose_name_plural': 'Информация о тикетах'},
        ),
        migrations.AddField(
            model_name='ticket',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
    ]
