# Generated by Django 2.0.6 on 2018-06-21 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20180621_0451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketcategory',
            name='Ticket',
        ),
        migrations.RemoveField(
            model_name='ticketcategory',
            name='status',
        ),
        migrations.AddField(
            model_name='ticket',
            name='chat_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='TicketCategory',
        ),
    ]
