# Generated by Django 2.0.6 on 2018-06-21 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20180621_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='chat_id',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
