# Generated by Django 2.0.6 on 2018-06-21 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20180621_1101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='username',
            new_name='surname',
        ),
    ]
