# Generated by Django 2.0.6 on 2018-06-23 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20180621_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='chat_messages',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
